apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmrs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmrs
  template:
    metadata:
      labels:
        app: openmrs
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for DB on openmrs-db:3306...";
              until nc -z openmrs-db 3306; do
                echo "Still waiting for DB...";
                sleep 3;
              done;
              echo "DB is ready!";
      containers:
        - name: openmrs
          image: bahmni/openmrs:latest
          env:
            - name: DB_HOST
              value: "openmrs-db"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "openmrs"
            - name: DB_USER
              value: "openmrs"
            - name: DB_PASSWORD
              value: "test"
            - name: DB_WAIT_FOR
              value: "openmrs-db:3306"   # this is the fix
          ports:
            - containerPort: 8080
