apiVersion: v1
kind: Service
metadata:
  name: openmrs
  labels:
    app: openmrs
spec:
  type: NodePort  # Changed from ClusterIP to NodePort
  selector:
    app: openmrs
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # Optional: explicitly set NodePort (must be between 30000-32767)