apiVersion: v1
kind: Service
metadata:
  name: crater-nginx
spec:
  type: LoadBalancer
  selector:
    app: crater-nginx
  ports:
    - name: http         
      port: 80
      targetPort: 80
    - name: https        
      port: 443
      targetPort: 443
