apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-documents
  labels:
    app: patient-documents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-documents
  template:
    metadata:
      labels:
        app: patient-documents
    spec:
      containers:
        - name: patient-documents
          image: 913524912266.dkr.ecr.ap-south-1.amazonaws.com/patient-documents:latest
          ports:
            - containerPort: 80
          env:
            - name: OPENMRS_HOST
              value: "openmrs"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: ecr-secret