apiVersion: apps/v1
kind: Deployment
metadata:
  name: crater-atomfeed
  labels:
    app: crater-atomfeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crater-atomfeed
  template:
    metadata:
      labels:
        app: crater-atomfeed
    spec:
      containers:
        - name: crater-atomfeed
          image: 913524912266.dkr.ecr.ap-south-1.amazonaws.com/crater-atomfeed:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: CRATER_USERNAME
              value: "superman@bahmni.org"
            - name: CRATER_PASSWORD
              value: "Crater123"
            - name: CRATER_ATOMFEED_DB_USERNAME
              value: "crater_atomfeed_user"
            - name: CRATER_ATOMFEED_DB_PASSWORD
              value: "passw0rd"
            - name: CRATER_ATOMFEED_DB_HOST
              value: "crater-atomfeed-db"
            - name: CRATER_ATOMFEED_DB_PORT
              value: "3306"
            - name: CRATER_ATOMFEED_DB_NAME
              value: "crater_atomfeed"
            - name: CRATER_URL
              value: "http://crater-nginx"
      restartPolicy: Always
