apiVersion: apps/v1
kind: Deployment
metadata:
  name: crater-atomfeed
  labels:
    app: crater-atomfeed
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: crater-atomfeed
  template:
    metadata:
      labels:
        app: crater-atomfeed
    spec:
      containers:
        - name: crater-atomfeed
          image: 913524912266.dkr.ecr.ap-south-1.amazonaws.com/crater-atomfeed:1.0.0
          ports:
            - containerPort: 80
          env:
            # Database Configuration
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://crater-atomfeed-db:3306/crater_atomfeed?useSSL=false&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "crater_atomfeed_user"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crater-atomfeed-secrets
                  key: db_password
 
            # OpenMRS Configuration
            - name: OPENMRS_URL
              value: "http://openmrs:8080/openmrs"
            - name: OPENMRS_ATOMFEED_USER
              value: "admin"
            - name: OPENMRS_ATOMFEED_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crater-atomfeed-secrets
                  key: openmrs_atomfeed_password
 
            # Crater Integration
            - name: CRATER_URL
              value: "http://crater-nginx"
            - name: CRATER_USERNAME
              value: "superman@bahmni.org"
            - name: CRATER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crater-atomfeed-secrets
                  key: crater_password
 
            # Mail Configuration
            - name: MAIL_SMTP_HOST
              value: "email-smtp.ap-south-1.amazonaws.com"
            - name: MAIL_SMTP_PORT
              value: "587"
            - name: MAIL_USER
              value: "AKIA3LET5U6POO5XGQ5S"
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crater-atomfeed-secrets
                  key: mail_password
 
            # Application Settings
            - name: SERVER_PORT
              value: "80"
            - name: TZ
              value: "UTC"
 
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 3
 
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
 
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
 
      imagePullSecrets:
        - name: ecr-secret