apiVersion: apps/v1
kind: Deployment
metadata:
  name: crater-atomfeed
  labels:
    app: crater-atomfeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crater-atomfeed
  template:
    metadata:
      labels:
        app: crater-atomfeed
    spec:
      containers:
        - name: crater-atomfeed
          image: 913524912266.dkr.ecr.ap-south-1.amazonaws.com/crater-atomfeed:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-secret
