apiVersion: v1
kind: Secret
metadata:
  name: crater-atomfeed-secret
type: Opaque
data:
  user-password: cGFzc3cwcmQ=                         # passw0rd
  openmrs_atomfeed_password: YWRtaW4=                 # admin
  crater_password: c3VwZXJzZWNyZXQ=                   # supersecret
  mail_password: QUJDMTIzNDU2Nzg5MA==                 # ABC1234567890