apiVersion: v1
kind: Secret
metadata:
  name: crater-atomfeed-secret
type: Opaque
data:
  user-password: cGFzc3cwcmQ=                   # passw0rd
  openmrs_atomfeed_password: YWRtaW4=           # admin
  crater_password: c3VwZXJtYW5AYmFobW5pLm9yZw== # superman@bahmni.org
  mail_password: QUtJQWZha2VQYXNzd29yZA==       # fake AWS mail password