apiVersion: v1
kind: Service
metadata:
  name: crater-atomfeed
  labels:
    app: crater-atomfeed
spec:
  type: ClusterIP
  selector:
    app: crater-atomfeed
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080  # Fixed: Changed from 80 to 8080