apiVersion: apps/v1
kind: Deployment
metadata:
  name: bahmni-web
  labels:
    app: bahmni-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bahmni-web
  template:
    metadata:
      labels:
        app: bahmni-web
    spec:
      containers:
        - name: bahmni-web
          image: 913524912266.dkr.ecr.ap-south-1.amazonaws.com/bahmni-web:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: bahmni-config
              mountPath: /usr/local/bahmni_config
      volumes:
        - name: bahmni-config
          hostPath:
            path: /home/ubuntu/HIMS-BACKUPS3/clinic-config
            type: Directory
      imagePullSecrets:
        - name: ecr-secret
